AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Guardfile'
    - 'Capfile'
    # Most of the errors given in these documents aren't correct
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/helpers/devise_helper.rb'
    - 'app/models/user.rb'
    - 'test/test_helper.rb'
    - 'app/controllers/teams_controller.rb'
    - 'app/controllers/questions_controller.rb'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
