RemoveUnusedMethodsInModelsCheck: {
  except_methods: [
  'User#new_with_session',
  'User#search'
  ]
}
RemoveUnusedMethodsInControllersCheck: { except_methods: [
  'RegistrationsController#account_update_params',
  'RegistrationsController#update_resource'
  ]
}